# Generated by Django 6.0.2 on 2026-02-18 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='イベント名')),
                ('start_time', models.DateTimeField(verbose_name='開始日時')),
                ('location', models.CharField(default='未定', max_length=100, verbose_name='場所')),
                ('description', models.TextField(blank=True, null=True, verbose_name='詳細・案内文')),
                ('url', models.URLField(blank=True, null=True, verbose_name='関連URL')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開中')),
            ],
            options={
                'verbose_name': 'イベント情報',
                'verbose_name_plural': 'イベント情報一覧',
            },
        ),
    ]
