# Generated by Django 6.0.2 on 2026-02-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTubeなどの動画URLを入力してください', null=True, verbose_name='動画URL'),
        ),
    ]
