# Generated by Django 6.0.2 on 2026-04-22 12:14

import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='写真タイトル')),
                ('image', models.ImageField(upload_to=events.models.tenant_directory_path, verbose_name='イベント写真')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='アップロード日時')),
            ],
            options={
                'verbose_name': 'イベント写真(S3テスト)',
                'verbose_name_plural': 'イベント写真(S3テスト)',
            },
        ),
    ]
