# Generated by Django 6.0.2 on 2026-04-23 06:05

import django.db.models.deletion
import events.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_cityadminprofile_options_and_more'),
        ('events', '0003_eventphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventphoto',
            options={'verbose_name': 'イベント写真', 'verbose_name_plural': 'イベント写真一覧'},
        ),
        migrations.AddField(
            model_name='eventphoto',
            name='politician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='対象自治会'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventphoto',
            name='image',
            field=models.ImageField(upload_to=events.models.event_photo_path, verbose_name='イベント写真'),
        ),
    ]
