# Generated by Django 6.0.2 on 2026-04-24 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_publicpageconfig'),
        ('events', '0004_alter_eventphoto_options_eventphoto_politician_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='politician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events_app_events', to='bot.politician', verbose_name='対象自治会'),
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('content', models.TextField(verbose_name='内容')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='公開中')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='bot.politician')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ一覧',
            },
        ),
    ]
