# Generated by Django 6.0.2 on 2026-04-26 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_publicpageconfig'),
        ('events', '0005_event_politician_announcement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル（例：総会出欠確認）')),
                ('description', models.TextField(blank=True, verbose_name='説明文・案内')),
                ('deadline', models.DateTimeField(verbose_name='回答締切日時')),
                ('is_active', models.BooleanField(default=True, verbose_name='回答受付中')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surveys', to='bot.politician', verbose_name='対象自治会')),
            ],
            options={
                'verbose_name': 'アンケート・回覧板',
                'verbose_name_plural': 'アンケート・回覧板一覧',
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respondent_name', models.CharField(max_length=100, verbose_name='回答者名（世帯主・班など）')),
                ('attendance', models.CharField(blank=True, choices=[('出席_賛成', '出席（または賛成）'), ('欠席_反対', '欠席（または反対）'), ('未定_保留', '未定（または保留）')], max_length=20, null=True, verbose_name='出欠・賛否')),
                ('comment', models.TextField(blank=True, verbose_name='ご意見・自由記述')),
                ('session_key', models.CharField(blank=True, max_length=100, verbose_name='ブラウザセッションID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='回答日時')),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='events.survey')),
            ],
            options={
                'verbose_name': '回答データ',
                'verbose_name_plural': '回答データ一覧',
                'constraints': [models.UniqueConstraint(fields=('survey', 'session_key'), name='unique_survey_response')],
            },
        ),
    ]
