# Generated by Django 6.0.2 on 2026-04-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_survey_surveyresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='医療機関名')),
                ('address', models.CharField(max_length=200, verbose_name='所在地')),
                ('phone', models.CharField(max_length=20, verbose_name='電話番号')),
                ('website_url', models.URLField(blank=True, null=True, verbose_name='公式サイトURL')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, help_text='駐車場や入口の正確な緯度（例: 31.907713）', max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, help_text='駐車場や入口の正確な経度（例: 131.420286）', max_digits=9, null=True, verbose_name='経度')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
            ],
            options={
                'verbose_name': '医療機関',
                'verbose_name_plural': '医療機関マスタ',
            },
        ),
    ]
