# Generated by Django 6.0.2 on 2026-04-28 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_medicalinstitution'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayDutySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='当番日')),
                ('department', models.CharField(help_text='例：内科、小児科', max_length=50, verbose_name='診療科目')),
                ('note', models.CharField(blank=True, help_text='例：受付は16時まで', max_length=200, verbose_name='備考')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='events.medicalinstitution', verbose_name='当番医院')),
            ],
            options={
                'verbose_name': '在宅医スケジュール',
                'verbose_name_plural': '在宅医スケジュール一覧',
                'unique_together': {('institution', 'date')},
            },
        ),
    ]
