# Generated by Django 6.0.2 on 2026-04-29 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_holidaydutyschedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 宮崎市中央、東諸県郡など', max_length=50, unique=True, verbose_name='医療圏名')),
                ('order', models.PositiveIntegerField(default=0, help_text='数字が小さいほどプルダウンの上部に表示されます', verbose_name='表示順')),
            ],
            options={
                'verbose_name': '医療圏',
                'verbose_name_plural': '医療圏マスタ',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AlterModelOptions(
            name='medicalinstitution',
            options={'ordering': ['name_kana', 'name'], 'verbose_name': '医療機関', 'verbose_name_plural': '医療機関マスタ'},
        ),
        migrations.RemoveField(
            model_name='holidaydutyschedule',
            name='department',
        ),
        migrations.AddField(
            model_name='medicalinstitution',
            name='department',
            field=models.CharField(blank=True, default='', help_text='例：内科、小児科', max_length=50, verbose_name='診療科目'),
        ),
        migrations.AddField(
            model_name='medicalinstitution',
            name='name_kana',
            field=models.CharField(blank=True, help_text='ひらがなで入力（ソート用）', max_length=100, verbose_name='ふりがな'),
        ),
        migrations.AlterField(
            model_name='holidaydutyschedule',
            name='institution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.medicalinstitution', verbose_name='当番医院'),
        ),
        migrations.AlterField(
            model_name='holidaydutyschedule',
            name='note',
            field=models.CharField(blank=True, max_length=200, verbose_name='備考'),
        ),
        migrations.AlterField(
            model_name='medicalinstitution',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度'),
        ),
        migrations.AlterField(
            model_name='medicalinstitution',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='経度'),
        ),
        migrations.AddField(
            model_name='medicalinstitution',
            name='area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='events.medicalarea', verbose_name='医療圏'),
        ),
    ]
