# Generated by Django 6.0.2 on 2026-05-07 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0018_funeralhall_municipality_condolence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='施設名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='収容人数')),
                ('is_active', models.BooleanField(default=True, verbose_name='予約受付中')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='対象自治会')),
            ],
            options={
                'verbose_name': '1. 貸出施設マスタ',
                'verbose_name_plural': '1. 貸出施設マスタ',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100, verbose_name='予約者・団体名')),
                ('user_phone', models.CharField(blank=True, max_length=20, verbose_name='連絡先電話番号')),
                ('date', models.DateField(verbose_name='利用日')),
                ('start_time', models.TimeField(verbose_name='開始時間')),
                ('end_time', models.TimeField(verbose_name='終了時間')),
                ('purpose', models.CharField(max_length=200, verbose_name='利用目的')),
                ('status', models.CharField(choices=[('PENDING', '承認待ち'), ('APPROVED', '承認済'), ('REJECTED', '却下'), ('CANCELLED', 'キャンセル')], default='PENDING', max_length=20, verbose_name='予約状況')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='reservations.facility', verbose_name='施設')),
            ],
            options={
                'verbose_name': '2. 予約一覧',
                'verbose_name_plural': '2. 予約一覧',
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
