# Generated by Django 6.0.2 on 2026-05-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='applicant_line_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='申請者のLINE User ID'),
        ),
    ]
