"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()
# .envファイルを読み込む設定
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-j30%1m0m8+b7!(i+ix13s(y52#n@#4kg_@+c7p#tiu43$fh=ac'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# 修正後
# ALLOWED_HOSTS = [
#     env('AWS_DOMAIN', default='aikouenkai.jp'), 
#     '3.113.83.98',  # あなたのサーバーの固定IPを直接追加
#     'localhost', 
#     '127.0.0.1'
# ]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 追加したアプリ
    'rest_framework',
    'django_bootstrap5',
    'members',
    'bot',
    'ai_engine',
    'events',
    'line_control',
    'import_export',
    'storages',
    'library',
    'accounting',
    'django.contrib.humanize',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

# ▼ 新しくPostgreSQLの設定を追記します
DATABASES = {
    'default': env.db('DATABASE_URL')        
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

# 日本語化とタイムゾーンの設定
LANGUAGE_CODE = 'ja'
TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True
USE_L10N = True
USE_TZ = True

# ==========================================
# Google Maps API Key
# ==========================================
GOOGLE_MAPS_API_KEY = 'AIzaSyA0X8JAMevCesNS9SBshTiWscXULjCokIA'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# core/settings.py の静的ファイル設定部分を以下に修正

STATIC_URL = '/static/'

# 🛡️ 防衛的設計: 開発用フォルダと本番用フォルダの完全分離

# ① 開発用（手動でWordファイルなどを置く「作業場」）
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# ② 本番用（コマンド実行時にDjangoが自動で全ファイルをかき集める「展示室」）
STATIC_ROOT = BASE_DIR / "staticfiles"

# アップロードされたファイル（PDFなど）の保存先とURLルールの設定
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# LINEやOpenAIのキーをenvから取得する準備（末尾などに追加）
LINE_CHANNEL_ACCESS_TOKEN = env('LINE_CHANNEL_ACCESS_TOKEN', default='')
LINE_CHANNEL_SECRET = env('LINE_CHANNEL_SECRET', default='')
OPENAI_API_KEY = env('OPENAI_API_KEY', default='')
GEMINI_API_KEY = env('GEMINI_API_KEY', default='')

# HTTPS設定（ACMを利用する場合に必要）
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = not DEBUG  # 本番環境のみリダイレクト

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

CSRF_TRUSTED_ORIGINS = ['https://aikouenkai.jp']

# ==========================================
# AWS S3 Settings
# ==========================================
AWS_ACCESS_KEY_ID = env('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = env('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = env('AWS_STORAGE_BUCKET_NAME')
AWS_S3_REGION_NAME = 'ap-northeast-1'

# 署名付きURLの有効期限（セキュリティ防衛：閲覧URLを1時間で無効化）
AWS_QUERYSTRING_AUTH = True
AWS_QUERYSTRING_EXPIRE = 3600

# 【削除する行】(Django 5.1以降では無効なため消します)
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

# 【追記するコード】(Django 6.0対応の新しい記述形式)
STORAGES = {
    "default": {
        "BACKEND": "storages.backends.s3boto3.S3Boto3Storage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}

MEDIA_URL = f'https://{AWS_STORAGE_BUCKET_NAME}.s3.amazonaws.com/'

# 🛡️ 運営側の防衛的視点: 未ログインユーザーがアクセスした際の、強制転送先URL（管理画面のログインへ誘導）
LOGIN_URL = '/admin/login/'
