# Generated by Django 6.0.2 on 2026-03-02 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='案内タイトル')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='紹介動画URL')),
            ],
            options={
                'verbose_name': '案内・教材',
                'verbose_name_plural': '案内・教材一覧',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=10)),
                ('text', models.TextField()),
                ('is_escalated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='自治会名')),
                ('slug', models.SlugField(unique=True, verbose_name='スラグ（URL用）')),
                ('line_channel_secret', models.CharField(max_length=255)),
                ('line_access_token', models.TextField()),
                ('openai_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('openai_assistant_id', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_model_name', models.CharField(default='gpt-4o', max_length=50)),
                ('system_prompt', models.TextField(blank=True, null=True)),
                ('gomi_municipality', models.CharField(blank=True, help_text='例: 宮崎市', max_length=50, null=True, verbose_name='ゴミ収集: 市町村')),
                ('gomi_district', models.CharField(blank=True, help_text='例: 北B地区', max_length=50, null=True, verbose_name='ゴミ収集: 地区')),
                ('label_group_1', models.CharField(default='グループ1', help_text='例: 役職名', max_length=50, verbose_name='グループ1の名称')),
                ('label_group_2', models.CharField(default='グループ2', help_text='例: 所属班', max_length=50, verbose_name='グループ2の名称')),
                ('label_group_3', models.CharField(default='グループ3', help_text='例: 専門部会', max_length=50, verbose_name='グループ3の名称')),
                ('label_note_1', models.CharField(default='備考1', help_text='例: 駐車場番号', max_length=50, verbose_name='備考1の名称')),
                ('label_note_2', models.CharField(default='備考2', help_text='例: 家族構成', max_length=50, verbose_name='備考2の名称')),
                ('label_note_3', models.CharField(default='備考3', help_text='例: 特記事項', max_length=50, verbose_name='備考3の名称')),
            ],
            options={
                'verbose_name': '自治会',
                'verbose_name_plural': '自治会一覧',
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=255)),
                ('last_completed_order', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.course')),
            ],
            options={
                'verbose_name': '案内情報の割り当て',
                'verbose_name_plural': '案内情報の割り当て',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='順番')),
                ('title', models.CharField(max_length=200, verbose_name='教材タイトル')),
                ('message_text', models.TextField(blank=True, verbose_name='メッセージ内容')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='解説動画URL')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='bot.course')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GarbageCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=50, verbose_name='市町村')),
                ('district', models.CharField(max_length=50, verbose_name='地区')),
                ('collection_date', models.DateField(verbose_name='収集日')),
                ('garbage_type', models.CharField(max_length=100, verbose_name='ゴミ種別')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='注意事項等')),
                ('other', models.TextField(blank=True, null=True, verbose_name='その他')),
            ],
            options={
                'verbose_name': 'ゴミ収集カレンダー',
                'verbose_name_plural': 'ゴミ収集カレンダー',
                'ordering': ['collection_date'],
                'unique_together': {('municipality', 'district', 'collection_date', 'garbage_type')},
            },
        ),
    ]
