# Generated by Django 6.0.2 on 2026-02-14 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', '利用者'), ('assistant', 'AI議員アバター'), ('system', 'システム')], max_length=10, verbose_name='送信者')),
                ('text', models.TextField(verbose_name='メッセージ内容')),
                ('is_escalated', models.BooleanField(default=False, verbose_name='相談窓口へ転送')),
                ('tokens', models.IntegerField(default=0, verbose_name='消費トークン数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='送信日時')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='members.aimember', verbose_name='メンバー')),
            ],
            options={
                'verbose_name': '会話ログ',
                'verbose_name_plural': '会話ログ一覧',
                'ordering': ['-created_at'],
            },
        ),
    ]
