# Generated by Django 6.0.2 on 2026-03-02 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagelog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.aimember'),
        ),
        migrations.AddField(
            model_name='politician',
            name='courses',
            field=models.ManyToManyField(blank=True, through='bot.CourseAssignment', to='bot.course'),
        ),
        migrations.AddField(
            model_name='event',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician'),
        ),
        migrations.AddField(
            model_name='courseassignment',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='current_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.course'),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician'),
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('line_user_id', 'current_course')},
        ),
    ]
