# Generated by Django 6.0.2 on 2026-02-19 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Politician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='議員名')),
                ('line_channel_secret', models.CharField(max_length=255, verbose_name='Channel Secret')),
                ('line_access_token', models.CharField(max_length=255, verbose_name='Access Token')),
                ('slug', models.SlugField(help_text='URLの一部になります', unique=True, verbose_name='識別パス')),
            ],
            options={
                'verbose_name': '議員',
                'verbose_name_plural': '議員一覧',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='イベント名')),
                ('date', models.DateTimeField(verbose_name='開催日時')),
                ('politician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='担当議員')),
            ],
            options={
                'verbose_name': '活動予定',
                'verbose_name_plural': '活動予定一覧',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='コース名')),
                ('description', models.TextField(blank=True, verbose_name='コース説明')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='担当議員')),
            ],
            options={
                'verbose_name': '教材コース',
                'verbose_name_plural': '教材コース一覧',
            },
        ),
        migrations.CreateModel(
            name='CourseContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(verbose_name='配信順序')),
                ('title', models.CharField(max_length=200, verbose_name='教材タイトル')),
                ('video_url', models.URLField(verbose_name='動画URL')),
                ('message_text', models.TextField(verbose_name='解説文')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='bot.course', verbose_name='コース')),
            ],
            options={
                'verbose_name': '教材コンテンツ',
                'verbose_name_plural': '教材コンテンツ一覧',
                'ordering': ['order'],
                'unique_together': {('course', 'order')},
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=100, verbose_name='LINE ID')),
                ('last_completed_order', models.PositiveIntegerField(default=0, verbose_name='完了済み順序')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.course', verbose_name='受講中のコース')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='担当議員')),
            ],
            options={
                'verbose_name': '受講進捗',
                'verbose_name_plural': '受講進捗一覧',
                'unique_together': {('line_user_id', 'current_course')},
            },
        ),
    ]
