# Generated by Django 6.0.2 on 2026-02-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_politician_event_course_coursecontent_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='ai_model_name',
            field=models.CharField(default='gpt-4o-mini', max_length=50, verbose_name='使用モデル名'),
        ),
        migrations.AddField(
            model_name='politician',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='OpenAI APIキー'),
        ),
        migrations.AddField(
            model_name='politician',
            name='system_prompt',
            field=models.TextField(default='あなたは誠実な政治家のアシスタントです。丁寧な言葉で答えてください。', verbose_name='AIシステムプロンプト'),
        ),
    ]
