# Generated by Django 6.0.2 on 2026-03-03 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='admin_users',
            field=models.ManyToManyField(blank=True, help_text='この自治会を管理できるユーザー（複数選択可）', related_name='managed_politicians', to=settings.AUTH_USER_MODEL, verbose_name='システム管理者'),
        ),
    ]
