# Generated by Django 6.0.2 on 2026-03-04 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_politician_admin_users'),
        ('members', '0002_tenantmemberprofile_note_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='配信タイトル（管理用）')),
                ('message_body', models.TextField(help_text='LINEで一斉送信されるメインの文章です。', verbose_name='配信メッセージ本文')),
                ('choice_1', models.CharField(default='無事です / 参加する', max_length=50, verbose_name='選択肢1')),
                ('choice_2', models.CharField(blank=True, default='助けが必要 / 不参加', max_length=50, null=True, verbose_name='選択肢2')),
                ('choice_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='選択肢3')),
                ('is_active', models.BooleanField(default=True, help_text='チェックを外すと回答を締め切ります', verbose_name='受付中')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='所属団体')),
            ],
            options={
                'verbose_name': '防災・アンケート配信',
                'verbose_name_plural': '防災・アンケート配信一覧',
            },
        ),
        migrations.CreateModel(
            name='EmergencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50, verbose_name='回答内容')),
                ('replied_at', models.DateTimeField(auto_now=True, verbose_name='回答日時')),
                ('ai_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.aimember', verbose_name='回答者（LINEアカウント）')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='bot.emergencyevent', verbose_name='対象イベント')),
            ],
            options={
                'verbose_name': '住民からの回答',
                'verbose_name_plural': '住民からの回答一覧',
                'unique_together': {('event', 'ai_member')},
            },
        ),
    ]
