# Generated by Django 6.0.2 on 2026-02-21 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_politician_ai_model_name_politician_openai_api_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, help_text='YouTubeなどの動画URLを入力してください', max_length=500, null=True, verbose_name='動画URL'),
        ),
    ]
