# Generated by Django 6.0.2 on 2026-02-22 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_course_video_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='openai_assistant_id',
            field=models.CharField(blank=True, help_text='Assistants APIを使用する場合は asst_ から始まるIDを入力してください', max_length=100, null=True, verbose_name='OpenAI アシスタントID'),
        ),
    ]
