# Generated by Django 6.0.2 on 2026-03-05 06:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_emergencyevent_emergencyresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyevent',
            name='target_group',
            field=models.CharField(blank=True, help_text='特定の班にのみ送信する場合に入力してください（空欄なら全員に送信）。例：1班', max_length=50, null=True, verbose_name='送信対象（班名など）'),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='target_past_answer',
            field=models.CharField(blank=True, help_text='例：「参加する」など（※過去配信を選択した場合のみ有効です）', max_length=50, null=True, verbose_name='絞り込み対象の回答'),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='target_past_event',
            field=models.ForeignKey(blank=True, help_text='特定のアンケートに回答した人にのみ送る場合に選択してください。', null=True, on_delete=django.db.models.deletion.SET_NULL, to='bot.emergencyevent', verbose_name='絞り込み対象の過去配信'),
        ),
    ]
