# Generated by Django 6.0.2 on 2026-03-05 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_emergencyevent_target_group_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyevent',
            name='target_group',
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='target_group_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='絞り込み: グループ1'),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='target_group_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='絞り込み: グループ2'),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='target_group_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='絞り込み: グループ3'),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='target_note_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='絞り込み: 備考1'),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='target_note_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='絞り込み: 備考2'),
        ),
        migrations.AddField(
            model_name='emergencyevent',
            name='target_note_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='絞り込み: 備考3'),
        ),
    ]
