# Generated by Django 6.0.2 on 2026-02-24 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0005_politician_openai_assistant_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='politician',
            options={'verbose_name': '自治会', 'verbose_name_plural': '自治会一覧'},
        ),
        migrations.AddField(
            model_name='politician',
            name='gomi_region',
            field=models.CharField(choices=[('miyazaki_kita_a', '宮崎市：北A地区'), ('miyazaki_kita_b', '宮崎市：北B地区'), ('miyazaki_minami_a', '宮崎市：南A地区'), ('miyazaki_minami_b', '宮崎市：南B地区'), ('none', '設定なし（または他市区町村）')], default='none', help_text='この自治会が該当するゴミ収集地区を選択してください。', max_length=50, verbose_name='ゴミ収集地区グループ'),
        ),
        migrations.AlterField(
            model_name='course',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='担当自治会'),
        ),
        migrations.AlterField(
            model_name='event',
            name='politician',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='担当自治会'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='role',
            field=models.CharField(choices=[('user', '利用者'), ('assistant', 'AIアシスタント'), ('system', 'システム')], max_length=10, verbose_name='送信者'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='name',
            field=models.CharField(max_length=100, verbose_name='自治会名'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='system_prompt',
            field=models.TextField(default='あなたは親切な自治会のアシスタントです。住民の質問に丁寧な言葉で答えてください。', verbose_name='AIシステムプロンプト'),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='担当自治会'),
        ),
    ]
