# Generated by Django 6.0.2 on 2026-03-05 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_remove_emergencyevent_target_group_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyevent',
            name='attached_file',
            field=models.FileField(blank=True, help_text='回覧板や詳細資料のPDFを添付できます（※選択するとLINEにURLが自動送信されます）。', null=True, upload_to='emergency_files/', verbose_name='添付ファイル (PDF等)'),
        ),
    ]
