# Generated by Django 6.0.2 on 2026-02-24 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0006_alter_politician_options_politician_gomi_region_and_more'),
        ('members', '0004_alter_aimember_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={},
        ),
        migrations.AlterModelOptions(
            name='coursecontent',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.AlterModelOptions(
            name='messagelog',
            options={},
        ),
        migrations.AlterModelOptions(
            name='politician',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='coursecontent',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='course',
            name='politician',
        ),
        migrations.RemoveField(
            model_name='messagelog',
            name='tokens',
        ),
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=200, verbose_name='案内タイトル'),
        ),
        migrations.AlterField(
            model_name='course',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='紹介動画URL'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='bot.course'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='message_text',
            field=models.TextField(blank=True, verbose_name='メッセージ内容'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='order',
            field=models.PositiveIntegerField(verbose_name='順番'),
        ),
        migrations.AlterField(
            model_name='coursecontent',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='解説動画URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='politician',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.politician'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='is_escalated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.aimember'),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='role',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='messagelog',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='politician',
            name='ai_model_name',
            field=models.CharField(default='gpt-4o', max_length=50),
        ),
        migrations.AlterField(
            model_name='politician',
            name='gomi_region',
            field=models.CharField(blank=True, choices=[('miyazaki_kita_a', '宮崎市：北A地区'), ('miyazaki_kita_b', '宮崎市：北B地区'), ('miyazaki_minami_a', '宮崎市：南A地区'), ('miyazaki_minami_b', '宮崎市：南B地区')], max_length=50, null=True, verbose_name='ゴミ収集地区グループ'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='line_access_token',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='politician',
            name='line_channel_secret',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='politician',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='openai_assistant_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='politician',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='スラグ（URL用）'),
        ),
        migrations.AlterField(
            model_name='politician',
            name='system_prompt',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='current_course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bot.course'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='last_completed_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='line_user_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='userprogress',
            name='politician',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician'),
        ),
        migrations.CreateModel(
            name='CourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='表示順')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.course')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician')),
            ],
            options={
                'verbose_name': '案内情報の割り当て',
                'verbose_name_plural': '案内情報の割り当て',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='politician',
            name='courses',
            field=models.ManyToManyField(blank=True, through='bot.CourseAssignment', to='bot.course'),
        ),
    ]
