# Generated by Django 6.0.2 on 2026-03-05 12:26

import bot.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_emergencyevent_attached_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyevent',
            name='attached_file',
            field=models.FileField(blank=True, help_text='回覧板や詳細資料のPDFを添付できます（※選択するとLINEにURLが自動送信されます）。', null=True, upload_to=bot.models.get_safe_filename, verbose_name='添付ファイル (PDF等)'),
        ),
    ]
