# Generated by Django 6.0.2 on 2026-02-25 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_alter_course_options_alter_coursecontent_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=50, verbose_name='市町村')),
                ('district', models.CharField(max_length=50, verbose_name='地区')),
                ('garbage_type', models.CharField(max_length=50, verbose_name='ゴミ種別')),
                ('week_pattern', models.CharField(choices=[('毎週', '毎週'), ('第1', '第1'), ('第2', '第2'), ('第3', '第3'), ('第4', '第4'), ('第5', '第5')], default='毎週', max_length=10, verbose_name='収集週')),
                ('weekday', models.CharField(choices=[('月', '月曜日'), ('火', '火曜日'), ('水', '水曜日'), ('木', '木曜日'), ('金', '金曜日'), ('土', '土曜日'), ('日', '日曜日')], max_length=10, verbose_name='収集曜日')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='注意事項等')),
                ('other', models.TextField(blank=True, null=True, verbose_name='その他')),
            ],
            options={
                'verbose_name': 'ゴミ収集スケジュール',
                'verbose_name_plural': 'ゴミ収集スケジュール',
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '案内・教材', 'verbose_name_plural': '案内・教材一覧'},
        ),
        migrations.AlterModelOptions(
            name='politician',
            options={'verbose_name': '自治会', 'verbose_name_plural': '自治会一覧'},
        ),
    ]
