# Generated by Django 6.0.2 on 2026-02-25 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_garbageschedule_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GarbageCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipality', models.CharField(max_length=50, verbose_name='市町村')),
                ('district', models.CharField(max_length=50, verbose_name='地区')),
                ('collection_date', models.DateField(verbose_name='収集日')),
                ('garbage_type', models.CharField(max_length=100, verbose_name='ゴミ種別')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='注意事項等')),
                ('other', models.TextField(blank=True, null=True, verbose_name='その他')),
            ],
            options={
                'verbose_name': 'ゴミ収集カレンダー',
                'verbose_name_plural': 'ゴミ収集カレンダー',
                'ordering': ['collection_date'],
                'unique_together': {('municipality', 'district', 'collection_date', 'garbage_type')},
            },
        ),
        migrations.DeleteModel(
            name='GarbageSchedule',
        ),
    ]
