# Generated by Django 6.0.2 on 2026-03-11 01:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0008_alter_emergencyevent_attached_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='city_code',
            field=models.CharField(blank=True, help_text='行政が横断管理するためのコード（例：宮崎市なら 45201 など）', max_length=20, null=True, verbose_name='所属市町村コード'),
        ),
        migrations.CreateModel(
            name='CityAdminProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_code', models.CharField(help_text='例：45201（宮崎市）', max_length=20, verbose_name='管轄する市町村コード')),
                ('city_name', models.CharField(help_text='例：宮崎市', max_length=50, verbose_name='自治体名')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='自治体管理者（システムユーザー）')),
            ],
        ),
    ]
