# Generated by Django 6.0.2 on 2026-03-11 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_politician_city_code_cityadminprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='district_code',
            field=models.CharField(blank=True, help_text='市町村内のさらに細かいエリアコード（例：吉村町なら yoshimura など）', max_length=50, null=True, verbose_name='所属地区・町名コード'),
        ),
    ]
