# Generated by Django 6.0.2 on 2026-03-01 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0009_garbagecalendar_delete_garbageschedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='gomi_district',
            field=models.CharField(blank=True, help_text='例: 北B地区', max_length=50, null=True, verbose_name='ゴミ収集: 地区'),
        ),
        migrations.AddField(
            model_name='politician',
            name='gomi_municipality',
            field=models.CharField(blank=True, help_text='例: 宮崎市', max_length=50, null=True, verbose_name='ゴミ収集: 市町村'),
        ),
    ]
