# Generated by Django 6.0.2 on 2026-03-11 06:35

import bot.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_politician_district_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityEmergencyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='タイトル（件名）')),
                ('message_body', models.TextField(verbose_name='メッセージ本文')),
                ('target_district_code', models.CharField(blank=True, help_text='特定の地区のみに送る場合に入力（例：yoshimura）。空欄なら管轄内すべての自治会へ一斉送信されます。', max_length=50, null=True, verbose_name='絞り込み対象の町・字コード')),
                ('attached_file', models.FileField(blank=True, help_text='避難所の地図などのPDFを添付できます。', null=True, upload_to=bot.models.get_safe_filename, verbose_name='添付ファイル (PDF等)')),
                ('is_active', models.BooleanField(default=True, verbose_name='受付中（有効）')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('city_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.cityadminprofile', verbose_name='作成者（市町村担当者）')),
            ],
        ),
    ]
