# Generated by Django 6.0.2 on 2026-03-01 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0010_politician_gomi_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='politician',
            name='gomi_region',
        ),
    ]
