# Generated by Django 6.0.2 on 2026-03-12 01:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0011_cityemergencyevent'),
        ('members', '0002_tenantmemberprofile_note_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityemergencyevent',
            name='choice_1',
            field=models.CharField(blank=True, help_text='例: 無事です', max_length=20, null=True, verbose_name='選択肢1'),
        ),
        migrations.AddField(
            model_name='cityemergencyevent',
            name='choice_2',
            field=models.CharField(blank=True, help_text='例: 支援が必要', max_length=20, null=True, verbose_name='選択肢2'),
        ),
        migrations.AddField(
            model_name='cityemergencyevent',
            name='choice_3',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='選択肢3'),
        ),
        migrations.CreateModel(
            name='CityEmergencyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=50, verbose_name='回答内容')),
                ('replied_at', models.DateTimeField(auto_now_add=True, verbose_name='回答日時')),
                ('ai_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.aimember', verbose_name='回答者')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.cityemergencyevent', verbose_name='対象の市町村配信')),
            ],
            options={
                'verbose_name': '市町村配信への回答',
                'verbose_name_plural': '市町村配信への回答',
                'unique_together': {('event', 'ai_member')},
            },
        ),
    ]
