# Generated by Django 6.0.2 on 2026-03-15 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0012_cityemergencyevent_choice_1_and_more'),
        ('members', '0002_tenantmemberprofile_note_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityemergencyevent',
            name='target_group_1',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='絞り込み: グループ1'),
        ),
        migrations.AddField(
            model_name='cityemergencyevent',
            name='target_group_2',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='絞り込み: グループ2'),
        ),
        migrations.AddField(
            model_name='cityemergencyevent',
            name='target_group_3',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='絞り込み: グループ3'),
        ),
        migrations.AddField(
            model_name='cityemergencyevent',
            name='target_note_1',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='絞り込み: 備考1'),
        ),
        migrations.AddField(
            model_name='cityemergencyevent',
            name='target_note_2',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='絞り込み: 備考2'),
        ),
        migrations.AddField(
            model_name='cityemergencyevent',
            name='target_note_3',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='絞り込み: 備考3'),
        ),
        migrations.CreateModel(
            name='CityMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_1', models.CharField(blank=True, max_length=50, null=True, verbose_name='グループ1')),
                ('group_2', models.CharField(blank=True, max_length=50, null=True, verbose_name='グループ2')),
                ('group_3', models.CharField(blank=True, max_length=50, null=True, verbose_name='グループ3')),
                ('note_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='備考1')),
                ('note_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='備考2')),
                ('note_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='備考3')),
                ('ai_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.aimember', verbose_name='対象住民')),
                ('city_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.cityadminprofile', verbose_name='管轄市町村')),
            ],
            options={
                'verbose_name': '市町村・住民プロフィール（独自タグ）',
                'verbose_name_plural': '市町村・住民プロフィール（独自タグ）',
                'unique_together': {('city_admin', 'ai_member')},
            },
        ),
    ]
