# Generated by Django 6.0.2 on 2026-03-17 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0013_cityemergencyevent_target_group_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cityadminprofile',
            options={'verbose_name': '市町村アカウント（担当者）', 'verbose_name_plural': '市町村アカウント（担当者）'},
        ),
        migrations.AlterModelOptions(
            name='cityemergencyevent',
            options={'verbose_name': '市町村・横断一斉送信（イベント）', 'verbose_name_plural': '市町村・横断一斉送信（イベント）'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'verbose_name': 'イベント・行事カレンダー', 'verbose_name_plural': 'イベント・行事カレンダー'},
        ),
        migrations.AlterModelOptions(
            name='messagelog',
            options={'verbose_name': '送信メッセージ履歴', 'verbose_name_plural': '送信メッセージ履歴'},
        ),
        migrations.AlterModelOptions(
            name='userprogress',
            options={'verbose_name': '住民のアクション履歴（学習進捗）', 'verbose_name_plural': '住民のアクション履歴（学習進捗）'},
        ),
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together=set(),
        ),
    ]
