# Generated by Django 6.0.2 on 2026-04-24 06:25

import bot.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0014_alter_cityadminprofile_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_visual', models.ImageField(blank=True, help_text='※スマホ画面の上部に表示される看板画像です（10MB以下の横長画像を推奨）', null=True, upload_to=bot.models.public_page_image_path, verbose_name='トップ画像')),
                ('accent_color', models.CharField(default='#2c3e50', help_text='例: #2c3e50（ヘッダー等の色を指定する16進数コード）', max_length=7, verbose_name='アクセントカラー')),
                ('welcome_text', models.TextField(default='私たちの自治会へようこそ。', help_text='トップページに表示されるメッセージです。', verbose_name='あいさつ文')),
                ('show_announcements', models.BooleanField(default=True, verbose_name='お知らせ一覧を表示する')),
                ('show_events', models.BooleanField(default=True, verbose_name='行事カレンダーを表示する')),
                ('show_library', models.BooleanField(default=True, verbose_name='公開資料室を表示する')),
                ('is_public', models.BooleanField(default=False, help_text='※チェックを入れると、外部からURLでアクセス可能になります。準備中は外してください。', verbose_name='ページを公開する')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('politician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page_config', to='bot.politician', verbose_name='対象自治会')),
            ],
            options={
                'verbose_name': '公開ページ（CMS）設定',
                'verbose_name_plural': '公開ページ（CMS）設定一覧',
            },
        ),
    ]
