# Generated by Django 6.0.2 on 2026-04-27 04:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0015_publicpageconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='BroadcastMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='例：令和6年度 総会のお知らせ配信', max_length=100, verbose_name='管理用タイトル（住民には見えません）')),
                ('message_text', models.TextField(help_text='※実際に住民のLINEに届く文章です。URL等もここに含めてください。', verbose_name='LINE送信テキスト')),
                ('is_sent', models.BooleanField(default=False, verbose_name='送信済')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='送信日時')),
                ('target_count', models.IntegerField(default=0, help_text='送信完了時にシステムが自動記録します', verbose_name='送信成功人数')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broadcasts', to='bot.politician', verbose_name='対象自治会')),
            ],
            options={
                'verbose_name': 'LINE一斉送信メッセージ',
                'verbose_name_plural': 'LINE一斉送信履歴',
                'ordering': ['-created_at'],
            },
        ),
    ]
