# Generated by Django 6.0.2 on 2026-04-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0016_broadcastmessage'),
        ('events', '0009_medicalarea_alter_medicalinstitution_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicpageconfig',
            name='target_medical_areas',
            field=models.ManyToManyField(blank=True, help_text='この地域にお住まいの住民へ表示する当番医のエリアを選択してください。', to='events.medicalarea', verbose_name='表示対象の医療圏'),
        ),
    ]
