# Generated by Django 6.0.2 on 2026-05-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0017_publicpageconfig_target_medical_areas'),
    ]

    operations = [
        migrations.CreateModel(
            name='FuneralHall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='葬祭場名')),
                ('address', models.CharField(max_length=200, verbose_name='所在地')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='緯度')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='経度')),
            ],
            options={
                'verbose_name': '葬祭場',
                'verbose_name_plural': '葬祭場マスタ',
                'ordering': ['municipality', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefecture', models.CharField(default='宮崎県', max_length=10, verbose_name='都道府県')),
                ('name', models.CharField(help_text='例：宮崎市、都城市', max_length=50, verbose_name='市町村名')),
            ],
            options={
                'verbose_name': '市町村',
                'verbose_name_plural': '市町村マスタ',
                'ordering': ['prefecture', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Condolence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deceased_name', models.CharField(max_length=100, verbose_name='故人氏名')),
                ('age', models.PositiveIntegerField(blank=True, null=True, verbose_name='年齢')),
                ('deceased_address', models.CharField(max_length=100, verbose_name='住所')),
                ('wake_datetime', models.DateTimeField(blank=True, null=True, verbose_name='通夜 日時')),
                ('funeral_datetime', models.DateTimeField(blank=True, null=True, verbose_name='告別式 日時')),
                ('ceremony_type', models.CharField(choices=[('仏式', '仏式'), ('神式', '神式'), ('キリスト教式', 'キリスト教式'), ('無宗教', '無宗教'), ('未定・その他', '未定・その他')], default='仏式', max_length=20, verbose_name='葬儀種別')),
                ('funeral_hall', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.funeralhall', verbose_name='葬祭場')),
            ],
            options={
                'verbose_name': 'おくやみ情報',
                'verbose_name_plural': 'おくやみ情報一覧',
            },
        ),
        migrations.AddField(
            model_name='funeralhall',
            name='municipality',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='bot.municipality', verbose_name='所在市町村'),
        ),
        migrations.AddField(
            model_name='publicpageconfig',
            name='target_condolence_areas',
            field=models.ManyToManyField(blank=True, help_text='この自治会ページに表示するおくやみ情報の市町村を選択してください。（例：宮崎市と近隣市町村を選択）', to='bot.municipality', verbose_name='おくやみ情報の表示エリア'),
        ),
    ]
