# Generated by Django 6.0.2 on 2026-05-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0018_funeralhall_municipality_condolence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='notification_line_id',
            field=models.CharField(blank=True, help_text='予約申請などの通知を受け取る役員のLINE User ID（U...）またはグループID（C...）', max_length=255, null=True, verbose_name='通知受信用LINE ID'),
        ),
    ]
