# Generated by Django 6.0.2 on 2026-05-14 07:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0019_politician_notification_line_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userprogress',
            unique_together={('line_user_id', 'current_course')},
        ),
        migrations.CreateModel(
            name='TenantLLMQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monthly_limit', models.IntegerField(default=100, help_text='このテナントが1ヶ月にAIを利用できる上限回数', verbose_name='月間AI利用上限回数')),
                ('current_month_usage', models.IntegerField(default=0, verbose_name='当月利用回数')),
                ('last_reset_date', models.DateField(default=django.utils.timezone.now, verbose_name='最終利用/リセット日')),
                ('politician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_quota', to='bot.politician', verbose_name='対象自治会')),
            ],
            options={
                'verbose_name': 'AI利用枠管理',
                'verbose_name_plural': 'AI利用枠管理一覧',
            },
        ),
    ]
