# Generated by Django 6.0.2 on 2026-05-19 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0020_alter_userprogress_unique_together_tenantllmquota'),
    ]

    operations = [
        migrations.AddField(
            model_name='politician',
            name='tenant_liff_id',
            field=models.CharField(blank=True, help_text='各団体が独自に取得したLIFF IDを入力してください。（空欄の場合は従来の共通LIFF IDが適用されます）', max_length=100, null=True, verbose_name='テナント専用 LIFF ID'),
        ),
    ]
