# Generated by Django 6.0.2 on 2026-02-23 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LineSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='デフォルト', max_length=100, verbose_name='設定名')),
                ('channel_secret', models.CharField(max_length=100, verbose_name='チャネルシークレット')),
                ('channel_access_token', models.CharField(max_length=500, verbose_name='アクセストークン')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'LINE連携設定',
                'verbose_name_plural': 'LINE連携設定',
            },
        ),
    ]
