# Generated by Django 6.0.2 on 2026-02-14 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AiMember',
            fields=[
                ('line_user_id', models.CharField(max_length=255, primary_key=True, serialize=False, verbose_name='LINEユーザーID')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='LINE表示名')),
                ('real_name', models.CharField(blank=True, max_length=100, verbose_name='氏名（本人申告）')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('existing_member_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='既存後援会ID（手動照合用）')),
                ('is_approved', models.BooleanField(default=False, verbose_name='後援会加入承認フラグ')),
                ('current_level', models.CharField(choices=[('beginner', '初心者'), ('intermediate', '中級者'), ('advanced', '上級者')], default='beginner', max_length=20, verbose_name='AIスキルレベル')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '後援会メンバー',
                'verbose_name_plural': '後援会メンバー一覧',
            },
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('beginner', '初心者'), ('intermediate', '中級者'), ('advanced', '上級者')], max_length=20)),
                ('title', models.CharField(max_length=200, verbose_name='教材タイトル')),
                ('content_text', models.TextField(verbose_name='教材本文')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='動画URL')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='配信順序')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '教材',
                'verbose_name_plural': '教材一覧',
                'ordering': ['level', 'order'],
            },
        ),
    ]
