# Generated by Django 6.0.2 on 2026-03-02 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AiMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_user_id', models.CharField(max_length=255, verbose_name='LINEユーザーID')),
                ('display_name', models.CharField(blank=True, max_length=100, verbose_name='LINE表示名')),
                ('real_name', models.CharField(blank=True, max_length=100, verbose_name='氏名（本人申告）')),
                ('address', models.TextField(blank=True, verbose_name='班名（部屋番号）')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('line_display_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='LINE登録名')),
                ('line_picture_url', models.URLField(blank=True, max_length=1000, null=True, verbose_name='LINEアイコン画像URL')),
                ('existing_member_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='既存名簿ID（手動照合用）')),
                ('is_approved', models.BooleanField(default=False, verbose_name='自治会加入承認フラグ')),
                ('current_level', models.CharField(choices=[('beginner', '初心者'), ('intermediate', '中級者'), ('advanced', '上級者')], default='beginner', max_length=20, verbose_name='AIスキルレベル')),
                ('registration_step', models.IntegerField(default=0, help_text='0:案内前, 1:名前待ち, 2:住所待ち, 3:登録完了', verbose_name='登録ステップ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('politician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='所属団体')),
            ],
            options={
                'verbose_name': '住民（メンバー）',
                'verbose_name_plural': '住民（メンバー）一覧',
                'unique_together': {('politician', 'line_user_id')},
            },
        ),
        migrations.CreateModel(
            name='TenantMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_id', models.CharField(max_length=50, verbose_name='管理番号')),
                ('official_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('official_address', models.CharField(blank=True, max_length=255, null=True, verbose_name='住所')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='生年月日')),
                ('head_of_household', models.CharField(blank=True, max_length=100, null=True, verbose_name='世帯主名')),
                ('relationship', models.CharField(blank=True, max_length=50, null=True, verbose_name='世帯主との続柄')),
                ('group_1', models.CharField(blank=True, max_length=100, null=True, verbose_name='グループ1')),
                ('group_2', models.CharField(blank=True, max_length=100, null=True, verbose_name='グループ2')),
                ('group_3', models.CharField(blank=True, max_length=100, null=True, verbose_name='グループ3')),
                ('note_1', models.CharField(blank=True, max_length=255, null=True, verbose_name='備考1')),
                ('ai_member', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='members.aimember', verbose_name='紐づくLINEアカウント')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='所属団体')),
            ],
        ),
    ]
