# Generated by Django 6.0.2 on 2026-03-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmemberprofile',
            name='note_2',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備考2'),
        ),
        migrations.AddField(
            model_name='tenantmemberprofile',
            name='note_3',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='備考3'),
        ),
    ]
