# Generated by Django 6.0.2 on 2026-02-21 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Curriculum',
        ),
    ]
