# Generated by Django 6.0.2 on 2026-03-17 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_tenantmemberprofile_note_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantmemberprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話番号'),
        ),
    ]
