# Generated by Django 6.0.2 on 2026-02-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_delete_curriculum'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimember',
            name='registration_step',
            field=models.IntegerField(default=0, help_text='0:案内前, 1:名前待ち, 2:住所待ち, 3:登録完了', verbose_name='登録ステップ'),
        ),
    ]
