# Generated by Django 6.0.2 on 2026-02-24 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_aimember_registration_step'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aimember',
            options={'verbose_name': '住民（メンバー）', 'verbose_name_plural': '住民（メンバー）一覧'},
        ),
        migrations.AlterField(
            model_name='aimember',
            name='existing_member_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='既存名簿ID（手動照合用）'),
        ),
        migrations.AlterField(
            model_name='aimember',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='自治会加入承認フラグ'),
        ),
    ]
