# Generated by Django 6.0.2 on 2026-03-17 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_tenantmemberprofile_phone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantmemberprofile',
            options={'verbose_name': '自治会名簿（メンバーデータ）', 'verbose_name_plural': '自治会名簿（メンバーデータ）'},
        ),
    ]
