# Generated by Django 6.0.2 on 2026-03-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_aimember_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aimember',
            name='line_display_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='LINE登録名'),
        ),
        migrations.AddField(
            model_name='aimember',
            name='line_picture_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='LINEアイコン画像URL'),
        ),
    ]
