# Generated by Django 6.0.2 on 2026-05-03 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bot', '0018_funeralhall_municipality_condolence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例：自治会費、防犯灯電気代など', max_length=50, verbose_name='科目名')),
                ('category_type', models.CharField(choices=[('INCOME', '収入'), ('EXPENSE', '支出')], max_length=10, verbose_name='収支区分')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='並び順')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='対象自治会')),
            ],
            options={
                'verbose_name': '勘定科目',
                'verbose_name_plural': '2. 勘定科目マスタ',
                'ordering': ['category_type', 'order'],
            },
        ),
        migrations.CreateModel(
            name='FiscalYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例：令和8年度', max_length=50, verbose_name='年度名')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('is_locked', models.BooleanField(default=False, help_text='チェックを入れると、この年度の伝票は一切追加・修正できなくなります。', verbose_name='会計ロック（締結済）')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='対象自治会')),
            ],
            options={
                'verbose_name': '会計年度',
                'verbose_name_plural': '1. 会計年度マスタ',
                'ordering': ['-start_date'],
                'unique_together': {('politician', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='取引日')),
                ('amount', models.IntegerField(verbose_name='金額')),
                ('description', models.CharField(max_length=200, verbose_name='摘要（詳細）')),
                ('receipt_image', models.ImageField(blank=True, null=True, upload_to='receipts/%Y/%m/', verbose_name='領収書画像')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='取消済')),
                ('cancelled_reason', models.CharField(blank=True, max_length=100, verbose_name='取消理由')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountcategory', verbose_name='勘定科目')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.fiscalyear', verbose_name='会計年度')),
                ('politician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bot.politician', verbose_name='対象自治会')),
            ],
            options={
                'verbose_name': '出納伝票',
                'verbose_name_plural': '3. 出納帳（伝票一覧）',
                'ordering': ['-date', '-id'],
            },
        ),
    ]
