# Generated by Django 6.0.2 on 2026-05-04 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(default=0, verbose_name='予算額')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.accountcategory', verbose_name='勘定科目')),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='accounting.fiscalyear', verbose_name='対象年度')),
            ],
            options={
                'verbose_name': '予算',
                'verbose_name_plural': '4. 予算管理マスタ',
                'ordering': ['category__category_type', 'category__order'],
                'unique_together': {('fiscal_year', 'category')},
            },
        ),
    ]
